(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))l(s);new MutationObserver(s=>{for(const n of s)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function r(s){const n={};return s.integrity&&(n.integrity=s.integrity),s.referrerPolicy&&(n.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?n.credentials="include":s.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function l(s){if(s.ep)return;s.ep=!0;const n=r(s);fetch(s.href,n)}})();const o={form:document.getElementById("task-form"),taskList:document.getElementById("tasks-list"),themeToggle:document.getElementById("themeToggle"),body:document.body};let i=[];function c(){return i}function g(e){i=e}function h(e,t){const r={id:Date.now().toString(),title:e,description:t};return i.push(r),r}function k(e){i=i.filter(t=>t.id!==e)}const d="tasks",u="theme";function m(e){localStorage.setItem(d,JSON.stringify(e))}function p(){return JSON.parse(localStorage.getItem(d))||[]}function T(e){localStorage.setItem(u,e)}function y(){return localStorage.getItem(u)||"theme-light"}function L({id:e,title:t,description:r}){return`
      <li class="task-list-item" data-id="${e}">
       <button class="task-list-item-btn">Delete</button>
       <h3>${t}</h3>
        <p>${r}</p>
        
      </li>
    `}function f(e){o.taskList.innerHTML=e.map(L).join("")}function v(e){const t=o.taskList.querySelector(`[data-id="${e}"]`);t&&t.remove()}function b(){const e=y();o.body.className=e}function E(){o.themeToggle.addEventListener("click",()=>{o.body.classList.toggle("theme-light"),o.body.classList.toggle("theme-dark");const e=o.body.classList.contains("theme-light")?"theme-light":"theme-dark";T(e)})}document.addEventListener("DOMContentLoaded",()=>{b(),E();const e=p();g(e),f(e)});o.form.addEventListener("submit",e=>{e.preventDefault();const t=o.form.taskName.value.trim(),r=o.form.taskDescription.value.trim();if(!t||!r){alert("Будь ласка, заповніть обидва поля: заголовок і опис завдання.");return}h(t,r),f(c()),m(c()),o.form.reset()});o.taskList.addEventListener("click",e=>{if(e.target.classList.contains("task-list-item-btn")){const t=e.target.closest("li").dataset.id;k(t),v(t),m(c())}});
//# sourceMappingURL=index.js.map
